#spring.application.name=Task-SubmissionService

server:
  port: 5004

spring:
  application:
    name: Task-SubmissionService
  #    it is the file name for the eureka to find
  jpa:
    hibernate:
      ddl-auto: update
    #    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/taskzy_tasksubmissionservice
    username: root
    password: 2106@2308Ud
    driver-class-name: com.mysql.cj.jdbc.Driver


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:5000/eureka/